package com.carhut.enums;

public enum RegistrationStatus {
    SUCCESS,
    INVALID_USERNAME,
    USERNAME_IN_USE,
    PASSWORDS_DO_NOT_MATCH,
    INVALID_EMAIL,
    INVALID_FIRST_NAME,
    INVALID_SURNAME,
    EMAIL_IN_USE,
    SHORT_PASSWORD,
    PASSWORD_DOES_NOT_CONTAIN_UPPER_CHARACTER,
    PASSWORD_DOES_NOT_CONTAIN_DIGIT,
    PASSWORD_DOES_NOT_CONTAIN_SPECIAL_CHARACTER,
    INVALID_PASSWORD,
    INVALID_REGISTRATION_TOKEN,
    REGISTRATION_TOKEN_ALREADY_SENT
}
