services:
  carhut_backend:
    container_name: carhut-backend-container
    image: carhut-backend-image
    build:
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      carhut_net:
        ipv4_address: 192.168.1.12

networks:
  carhut_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
