package com.carhut.enums;

public enum ServiceStatusEntity {
    SUCCESS,
    OBJECT_NOT_FOUND,
    OBJECT_NOT_FOUND_EXCEPTIONALLY,
    OBJECT_COULD_NOT_BE_SAVED,
    OBJECT_COULD_NOT_BE_SAVED_EXCEPTIONALLY,
    OBJECT_COULD_NOT_BE_DELETED,
    OBJECT_COULD_NOT_BE_DELETED_EXCEPTIONALLY,
    OBJECT_COULD_NOT_BE_UPDATED,
    OBJECT_COULD_NOT_BE_UPDATED_EXCEPTIONALLY,
    ERROR
}
