name: Build and test CarHut

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: 'x64'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build project
        run: |
          mvn clean install ./CarHut \
            -Dspring.datasource.url=${{ secrets.H2_EMBEDDED_DATA_SOURCE }} \
            -Dspring.datasource.username=${{ secrets.H2_EMBEDDED_DATA_SOURCE_USERNAME }} \
            -Dspring.datasource.password=${{ secrets.H2_EMBEDDED_DATA_SOURCE_PASSWORD }} \
            -Dspring.mail.host=${{ secrets.MAIL_HOST }} \
            -Dspring.mail.port=${{ secrets.MAIL_PORT }} \
            -Dspring.mail.username=${{ secrets.MAIL_USERNAME }} \
            -Dspring.mail.password=${{ secrets.MAIL_PASSWORD }} \
            -Dspring.security.oauth2.resourceserver.opaquetoken.client-id=${{ secrets.OAUTH2_GOOGLE_ID }} \
            -Dspring.security.oauth2.resourceserver.opaquetoken.client-secret=${{ secrets.OAUTH2_GOOGLE_SECRET }} \
            -Dspring.security.oauth2.resourceserver.opaquetoken.introspection-uri=${{ secrets.OAUTH2_GOOGLE_INTROSPECTION_URL }}
